"""add intro flag

Revision ID: 08a6d82acf7c
Revises: d73178291150
Create Date: 2026-02-03 20:07:56.885012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a6d82acf7c'
down_revision: Union[str, Sequence[str], None] = 'd73178291150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('closed_menu_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'closed_menu_flag')
    # ### end Alembic commands ###
