"""add vk_magazine to magazines

Revision ID: 09617f64a26b
Revises: c7ec05cd28b7
Create Date: 2026-03-05 08:58:18.837511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09617f64a26b'
down_revision: Union[str, Sequence[str], None] = 'c7ec05cd28b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('vk_magazine', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'vk_magazine')
    # ### end Alembic commands ###
