"""add_is_promo_active_to_magazines

Revision ID: 3941f827c321
Revises: 0bf08a6e104f
Create Date: 2026-02-22 13:16:32.754637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3941f827c321'
down_revision: Union[str, Sequence[str], None] = '0bf08a6e104f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('is_promo_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'is_promo_active')
    # ### end Alembic commands ###
