"""Delete ChannelState table

Revision ID: 3ecbba7daf57
Revises: 5a13530a8785
Create Date: 2026-02-13 11:22:49.640232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ecbba7daf57'
down_revision: Union[str, Sequence[str], None] = '5a13530a8785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_states_channel_id'), table_name='channel_states')
    op.drop_table('channel_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('magazine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], name=op.f('channel_states_magazine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_states_pkey'))
    )
    op.create_index(op.f('ix_channel_states_channel_id'), 'channel_states', ['channel_id'], unique=True)
    # ### end Alembic commands ###
