"""split first request flags

Revision ID: 587efbbe908b
Revises: 08a6d82acf7c
Create Date: 2026-02-04 13:59:18.916224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587efbbe908b'
down_revision: Union[str, Sequence[str], None] = '08a6d82acf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_catalog_request', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('first_info_request', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('users', 'is_first_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_request', sa.BOOLEAN(), autoincrement=False, nullable=True, server_default='true'))
    op.drop_column('users', 'first_info_request')
    op.drop_column('users', 'first_catalog_request')
    # ### end Alembic commands ###
