"""add_first_to_feedback

Revision ID: 590195e239a5
Revises: f12ffb088832
Create Date: 2026-02-22 19:53:59.823636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590195e239a5'
down_revision: Union[str, Sequence[str], None] = 'f12ffb088832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_to_feedback', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_to_feedback')
    # ### end Alembic commands ###
