"""add_vk_id_platform_payment_session

Revision ID: 8cc8bc9e0f35
Revises: 590195e239a5
Create Date: 2026-02-25 15:36:50.804304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc8bc9e0f35'
down_revision: Union[str, Sequence[str], None] = '590195e239a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_sessions_token'), 'payment_sessions', ['token'], unique=True)
    op.add_column('payments', sa.Column('platform', sa.String(length=10), server_default='telegram', nullable=False))
    op.add_column('users', sa.Column('vk_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'vk_id')
    op.drop_column('payments', 'platform')
    op.drop_index(op.f('ix_payment_sessions_token'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    # ### end Alembic commands ###
