"""add_analytics_columns

Revision ID: aaa54b2bcaf3
Revises: 3ecbba7daf57
Create Date: 2026-02-20 11:18:01.346187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa54b2bcaf3'
down_revision: Union[str, Sequence[str], None] = '3ecbba7daf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wb_clicked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wb_clicked_at')
    # ### end Alembic commands ###
