"""add_subscribed_to_author_flag

Revision ID: ba212ce9a1fb
Revises: e5db8f6d0256
Create Date: 2026-02-21 17:22:04.207106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba212ce9a1fb'
down_revision: Union[str, Sequence[str], None] = 'e5db8f6d0256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed_to_author', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed_to_author')
    # ### end Alembic commands ###
