"""add_service_tracking

Revision ID: f12ffb088832
Revises: ad3ca9c176af
Create Date: 2026-02-22 18:42:16.794967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12ffb088832'
down_revision: Union[str, Sequence[str], None] = 'ad3ca9c176af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service_registered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('service_level', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service_level')
    op.drop_column('users', 'service_registered_at')
    # ### end Alembic commands ###
